{{- if .Values.persistence.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "wikimedia.fullname" . }}-mediawiki
  labels:
    app: {{ template "wikimedia.name" . }}
    chart: {{ template "wikimedia.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{ include "wikimedia.storageClass" . }}
{{- end -}}
