apiVersion: v1
kind: Secret
metadata:
  name: {{ template "wikimedia.fullname" . }}
  labels:
    app: {{ template "wikimedia.name" . }}
    chart: {{ template "wikimedia.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{ if .Values.mediawikiPassword }}
  wikimedia-password: {{ .Values.wikimediaPassword | b64enc | quote }}
  {{ else }}
  wikimedia-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.smtpPassword }}
  smtp-password: {{ .Values.smtpPassword | b64enc | quote }}
  {{ end }}
